### ISSUE TITLE
LSTM_Test 

### ISSUE THREAD

**Issue by ghost** [adityatb/noise-reduction-using-rnn#1]
Hello and thank you for sharing your codes,
Is there any reason that LSTM_Train and LSTM_Test are the same here ? how we can use our created model to produce audio outputs?

**Comment by JSai23** [comment]
Did anyone find a solution to this, it is really frustrating?

**Comment by adityatb** [comment]
This issue is now in duplicate, so I'm closing this one. I have left a response on the other issue.
In short: unfortunately, there is no longer a script that outputs files from the trained models. I am focussing on a script that can improve training and evaluate against the metrics mentioned in the paper... like SNR, SIR etc.
